version: '3'

services:

  m-plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: m-plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - VERSION=docker
    volumes:
      - ${MEDIA}/movies:/media/movies
      - ${MEDIA}/series:/media/series
      - ${MEDIA}/anime:/media/anime
    restart: unless-stopped

  m-samba:
    image: dperson/samba
    container_name: m-samba
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
    volumes:
      - ${DONWLOADS}:/downloads
      - ${MEDIA}:/media
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped

  m-qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: m-qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG}/qbittorrent:/config
      - ${DONWLOADS}/torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  m-jdownloader2:
    container_name: m-jdownloader2
    image: jlesage/jdownloader-2
    ports:
      - "5800:5800"
    volumes:
      - ${CONFIG}/jdownloader2:/config:rw
      - ${DONWLOADS}/jdownloader:/donwloads:rw
    environment:
      - TZ=America/Mexico_City
      - LANG=es_MX.UTF-8
      - KEEP_APP_RUNNING=1
      - DARK_MODE=1
      - SECURE_CONNECTION=1